# Generated by Django 6.1.1 on 2026-10-06 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('posicao', models.PositiveIntegerField()),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='sugestao.artigo')),
            ],
        ),
        migrations.CreateModel(
            name='Trecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveIntegerField()),
                ('texto', models.TextField()),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='sugestao.secao')),
            ],
        ),
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('rejeitada', 'Rejeitada'), ('substituida', 'Substituída')], default='pendente', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('decidida_em', models.DateTimeField(blank=True, null=True)),
                ('trecho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes', to='sugestao.trecho')),
            ],
        ),
        migrations.CreateModel(
            name='VersaoArtigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='sugestao.artigo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='secao',
            constraint=models.UniqueConstraint(fields=('artigo', 'posicao'), name='uma_posicao_por_artigo'),
        ),
        migrations.AddConstraint(
            model_name='trecho',
            constraint=models.UniqueConstraint(fields=('secao', 'posicao'), name='uma_posicao_por_secao'),
        ),
        migrations.AddConstraint(
            model_name='sugestao',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'aceita')), fields=('trecho',), name='uma_aceita_por_trecho'),
        ),
        migrations.AddConstraint(
            model_name='sugestao',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pendente')), fields=('trecho',), name='uma_pendente_por_trecho'),
        ),
        migrations.AddConstraint(
            model_name='sugestao',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pendente', 'aceita', 'rejeitada', 'substituida'])), name='status_valido'),
        ),
        migrations.AddConstraint(
            model_name='sugestao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decidida_em__isnull', True), ('status', 'pendente')), models.Q(('decidida_em__isnull', False), ('status__in', ['aceita', 'rejeitada', 'substituida'])), _connector='OR'), name='decisao_tem_data'),
        ),
        migrations.AddIndex(
            model_name='versaoartigo',
            index=models.Index(fields=['artigo', '-criada_em'], name='idx_artigo_versoes_recentes'),
        ),
    ]
